### ISSUE TITLE
View current direction

### ISSUE THREAD

**Issue by karlstahre** [DIT112-V21/group-12#19]
### User story
As an application car driver I want to be able to see in which direction the car is driving on my smartphone screen so that the driver of the car knows in which direction the car will drive when standing still.

***
### Acceptance criteria

- The application car driver must be able to view the current direction of the car at all times. The direction of the car can only be changed by input of the application car driver.
- If the car hits an obstacle, the car will change the direction of the car to “backward”.

**Comment by MajaLinder** [comment]
- [x] Implement arrow buttons depressed 
- [x] Only one of the forward and backward arrow buttons can be activated at a time
- [x] Only one of the left and right arrow buttons can be activated at a time

**Comment by MajaLinder** [comment]
- [ ] When the car stands still the arrow buttons get deactivated
- [x] Only one arrow button can be activated at a time

**Comment by karlstahre** [comment]
- [x] Do not store previous mode settings after a reset
- [x] Make pressing the forward arrow after a brake be sufficient to start the car going forward again

**Comment by karlstahre** [comment]
- [x] Code refactoring
