### ISSUE TITLE
View current speed mode

### ISSUE THREAD

**Issue by karlstahre** [DIT112-V21/group-12#20]
### User story
As an application car driver I want to be able to see in what speed mode the car is currently driving on my smartphone screen so that the car driver easily can change speed mode to one that is not currently used.

***
### Acceptance criteria

- There are four different speed modes that accelerates the car to different speeds.
- The car can be put in the different speed at all times as long as the car has been put in drive or reverse.

**Comment by MajaLinder** [comment]
- [x] Box showing which speed mode the car is currently driving in 
- [x] Implement "speed" button depressed 
- [x] Implement "1-4" buttons depressed
- [x] Only one mode button can be activated at a time
- [x] Only one number button can be activated at a time
- [x] The number button activated will correspond to the activated mode

**Comment by MajaLinder** [comment]
- [x] Deactivate buttons when the car is standing still

**Comment by karlstahre** [comment]
- [x] Do not store previous mode settings after a reset
- [x] Make pressing the forward arrow after a brake be sufficient to start the car going forward again

**Comment by karlstahre** [comment]
- [x] Code refactoring
