### ISSUE TITLE
View current speed

### ISSUE THREAD

**Issue by karlstahre** [DIT112-V21/group-12#21]
### User story
As an application car driver I want to be able to see in which speed the car is moving on my smartphone screen at any given point in time so that the car driver knows in which speed the car is going.

***
### Acceptance criteria

- The application car driver must be able to view the current speed of the car at all times. 
- The current speed should be continuously updated based on the driver's maneuvering of the car.

**Comment by MajaLinder** [comment]
- [x] Extract speed from SMCE in real time
- [x] Show exact speed continuously on the driving screen
