### ISSUE TITLE
View current steering mode

### ISSUE THREAD

**Issue by karlstahre** [DIT112-V21/group-12#22]
### User story
As an application car driver I want to be able to see in which steering mode the car is in on my smartphone screen so that the driver of the car can know in which direction the car will drive when instructed to move.
***

### Acceptance criteria
- The application car driver must be able to view the current steering mode of the car at all times. The steering mode of the car can only be changed by input of the application car driver.

**Comment by MajaLinder** [comment]
- [x] Box showing which angle mode the car is currently driving in 
- [x] Implement "angle" button depressed 
- [x] Implement "1-4" buttons depressed
- [x] Only one mode button can be activated at a time
- [x] Only one number button can be activated at a time
- [x] The number button activated will correspond to the activated mode

**Comment by MajaLinder** [comment]
- [x] Deactivate buttons when the car is standing still

**Comment by karlstahre** [comment]
- [x] Do not store previous mode settings after a reset
- [x] Make pressing the forward arrow after a brake be sufficient to start the car going forward again

**Comment by karlstahre** [comment]
- [x] Code refactoring
