### ISSUE TITLE
Create new dance moves

### ISSUE THREAD

**Issue by b4rdha** [DIT112-V21/group-12#31]
### User story
As an application car driver I want to be able to create new dance moves and save the movements for future use so that I can make my car dance my favorite dance moves.
***
### Acceptance criteria

- A created dance move can consist of minimum 2 and maximum 20 different driving/steering directions.
- A created dance move can be maximum 10 seconds long.
- When creating a new dance move the application car driver must be able to use all speed, angle and braking modes available in the application.

**Comment by amandaturquis** [comment]
- [x] Create new activity with extra recording buttons
- [x] Add a timer  @MajaLinder @karlstahre 
- [x] Fix activity between dance moves and new dance moves @meissalim 
- [x] Create start and save recording buttons
- [x] Start/Stop button
- [x] Fix design for toggle button
- [x] Add stopwatch and save duration for an individual move
- [x] Save the sequence of dance instructions
- [x] Implement constraints on the amount of steering directions
- [x] Extract the CreatedDanceMove direction and duration attributes and send them with MQTT to the Arduino file
- [x] Handle CreatedDanceMove attributes in Arduino and make the car follow those instructions
- [x] Make it impossible to add the same name to more than one created dance move
- [ ] Save to and retrieve from database
