### ISSUE TITLE
View current braking mode

### ISSUE THREAD

**Issue by MajaLinder** [DIT112-V21/group-12#38]
### User Story
As an application car driver I want to be able to see in which braking mode the car is in on my smartphone screen so that the driver of the car can know how smoothly the car will brake.

***
### Acceptance Criteria
- The application car driver must be able to view the current braking mode of the car at all times. 
- The braking mode of the car can only be changed by input of the application car driver.

**Comment by MajaLinder** [comment]
- [x] Box showing which brake mode the car is currently driving in 
- [x] Implement "brake" button depressed 
- [x] Implement "1-4" buttons depressed
- [x] Only one mode button can be activated at a time
- [x] Only one number button can be activated at a time
- [x] The number button activated will correspond to the activated mode

**Comment by MajaLinder** [comment]
- [x] Deactivate buttons when the car is standing still

**Comment by karlstahre** [comment]
- [x] Do not store previous mode settings after a reset
- [x] Make pressing the forward arrow after a brake be sufficient to start the car going forward again

**Comment by karlstahre** [comment]
- [x] Code refactoring
